# -*- coding: utf-8 -*-
"""
配置模块统一入口
从 settings.py 导出配置，保持向后兼容
"""
from app.config.settings import (
    settings,
    MYSQL_DATABASE_URL,
    LOCAL_BIG_MODEL_PARAMS,
    DATABASE_SCHEMA,
    DATABASE_POOL_SIZE,
    DATABASE_POOL_MAX_OVERFLOW,
    DATABASE_POOL_TIMEOUT,
    DATABASE_POOL_RECYCLE,
)

# MinIO 配置导出
MINIO_ENDPOINT = settings.MINIO_ENDPOINT
MINIO_ACCESS_KEY = settings.MINIO_ACCESS_KEY
MINIO_SECRET_KEY = settings.MINIO_SECRET_KEY
MINIO_BUCKET = settings.MINIO_BUCKET
MINIO_SECURE = settings.MINIO_SECURE

# Milvus 配置导出
MILVUS_HOST = settings.MILVUS_HOST
MILVUS_PORT = settings.MILVUS_PORT
MILVUS_COLLECTION = settings.MILVUS_COLLECTION
MILVUS_INDEX_CONFIG = settings.MILVUS_INDEX_CONFIG
MILVUS_SEARCH_CONFIG = settings.MILVUS_SEARCH_CONFIG

# Embedding 配置导出
EMBEDDING_API_URL = settings.EMBEDDING_API_URL
EMBEDDING_DIMENSION = settings.EMBEDDING_DIMENSION
EMBEDDING_TIMEOUT = settings.EMBEDDING_TIMEOUT
EMBEDDING_BATCH_SIZE = settings.EMBEDDING_BATCH_SIZE

# Redis/Celery 配置导出
REDIS_HOST = settings.REDIS_HOST
REDIS_PORT = settings.REDIS_PORT
REDIS_DB_BROKER = settings.REDIS_DB_BROKER
REDIS_DB_BACKEND = settings.REDIS_DB_BACKEND
CELERY_BROKER_URL = settings.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = settings.CELERY_RESULT_BACKEND
CELERY_CONFIG = settings.CELERY_CONFIG
CELERY_TASK_TIME_LIMIT = settings.CELERY_TASK_TIME_LIMIT

# Docling 配置导出
DOCLING_TIMEOUT = settings.DOCLING_TIMEOUT
DOCLING_MAX_WORKERS = settings.DOCLING_MAX_WORKERS

# Template 配置导出
TEMPLATE_COLLECTION_NAME = settings.TEMPLATE_COLLECTION_NAME
TEMPLATE_DUPLICATE_THRESHOLD = settings.TEMPLATE_DUPLICATE_THRESHOLD

__all__ = [
    'settings',
    # 数据库
    'MYSQL_DATABASE_URL',
    'LOCAL_BIG_MODEL_PARAMS',
    'DATABASE_SCHEMA',
    'DATABASE_POOL_SIZE',
    'DATABASE_POOL_MAX_OVERFLOW',
    'DATABASE_POOL_TIMEOUT',
    'DATABASE_POOL_RECYCLE',
    # MinIO
    'MINIO_ENDPOINT',
    'MINIO_ACCESS_KEY',
    'MINIO_SECRET_KEY',
    'MINIO_BUCKET',
    'MINIO_SECURE',
    # Milvus
    'MILVUS_HOST',
    'MILVUS_PORT',
    'MILVUS_COLLECTION',
    'MILVUS_INDEX_CONFIG',
    'MILVUS_SEARCH_CONFIG',
    # Embedding
    'EMBEDDING_API_URL',
    'EMBEDDING_DIMENSION',
    'EMBEDDING_TIMEOUT',
    'EMBEDDING_BATCH_SIZE',
    # Redis/Celery
    'REDIS_HOST',
    'REDIS_PORT',
    'REDIS_DB_BROKER',
    'REDIS_DB_BACKEND',
    'CELERY_BROKER_URL',
    'CELERY_RESULT_BACKEND',
    'CELERY_CONFIG',
    'CELERY_TASK_TIME_LIMIT',
    # Docling
    'DOCLING_TIMEOUT',
    'DOCLING_MAX_WORKERS',
    # Template
    'TEMPLATE_COLLECTION_NAME',
    'TEMPLATE_DUPLICATE_THRESHOLD',
]